package defpackage;

import defpackage.b00;
/* renamed from: bsb  reason: default package */
/* loaded from: classes.dex */
public abstract class bsb {
    public static final b00 a;
    public static final b00 b;
    public static final b00 c;
    public static final b00 d;
    public static final b00 e;
    public static final b00 f;
    public static final b00 g;
    public static final b00 h;
    public static final b00 i;
    public static final b00 j;
    public static final b00 k;
    public static final b00 l;
    public static final b00 m;
    public static final b00 n;
    public static final b00 o;
    public static final b00 p;
    public static final b00 q;
    public static final b00 r;
    public static final b00 s;
    public static final b00 t;
    public static final b00 u;
    public static final b00 v;
    public static final b00 w;
    public static final b00 x;
    public static final b00 y;
    public static final b00 z;

    static {
        b00.a b2 = b00.b();
        b2.c(3);
        b2.b("Google Play In-app Billing API version is less than 3");
        a = b2.a();
        b00.a b3 = b00.b();
        b3.c(3);
        b3.b("Google Play In-app Billing API version is less than 9");
        b = b3.a();
        b00.a b4 = b00.b();
        b4.c(3);
        b4.b("Billing service unavailable on device.");
        c = b4.a();
        b00.a b5 = b00.b();
        b5.c(5);
        b5.b("Client is already in the process of connecting to billing service.");
        d = b5.a();
        b00.a b6 = b00.b();
        b6.c(5);
        b6.b("The list of SKUs can't be empty.");
        e = b6.a();
        b00.a b7 = b00.b();
        b7.c(5);
        b7.b("SKU type can't be empty.");
        f = b7.a();
        b00.a b8 = b00.b();
        b8.c(5);
        b8.b("Product type can't be empty.");
        g = b8.a();
        b00.a b9 = b00.b();
        b9.c(-2);
        b9.b("Client does not support extra params.");
        h = b9.a();
        b00.a b10 = b00.b();
        b10.c(5);
        b10.b("Invalid purchase token.");
        i = b10.a();
        b00.a b11 = b00.b();
        b11.c(6);
        b11.b("An internal error occurred.");
        j = b11.a();
        b00.a b12 = b00.b();
        b12.c(5);
        b12.b("SKU can't be null.");
        k = b12.a();
        b00.a b13 = b00.b();
        b13.c(0);
        l = b13.a();
        b00.a b14 = b00.b();
        b14.c(-1);
        b14.b("Service connection is disconnected.");
        m = b14.a();
        b00.a b15 = b00.b();
        b15.c(-3);
        b15.b("Timeout communicating with service.");
        n = b15.a();
        b00.a b16 = b00.b();
        b16.c(-2);
        b16.b("Client does not support subscriptions.");
        o = b16.a();
        b00.a b17 = b00.b();
        b17.c(-2);
        b17.b("Client does not support subscriptions update.");
        p = b17.a();
        b00.a b18 = b00.b();
        b18.c(-2);
        b18.b("Client does not support get purchase history.");
        q = b18.a();
        b00.a b19 = b00.b();
        b19.c(-2);
        b19.b("Client does not support price change confirmation.");
        r = b19.a();
        b00.a b20 = b00.b();
        b20.c(-2);
        b20.b("Play Store version installed does not support cross selling products.");
        s = b20.a();
        b00.a b21 = b00.b();
        b21.c(-2);
        b21.b("Client does not support multi-item purchases.");
        t = b21.a();
        b00.a b22 = b00.b();
        b22.c(-2);
        b22.b("Client does not support offer_id_token.");
        u = b22.a();
        b00.a b23 = b00.b();
        b23.c(-2);
        b23.b("Client does not support ProductDetails.");
        v = b23.a();
        b00.a b24 = b00.b();
        b24.c(-2);
        b24.b("Client does not support in-app messages.");
        w = b24.a();
        b00.a b25 = b00.b();
        b25.c(-2);
        b25.b("Client does not support alternative billing.");
        x = b25.a();
        b00.a b26 = b00.b();
        b26.c(5);
        b26.b("Unknown feature");
        y = b26.a();
        b00.a b27 = b00.b();
        b27.c(-2);
        b27.b("Play Store version installed does not support get billing config.");
        z = b27.a();
    }
}
