package defpackage;

import defpackage.s03;
/* renamed from: u7c  reason: default package */
/* loaded from: classes.dex */
public final class u7c implements kq6 {
    public static final s03 A;
    public static final s03 B;
    public static final s03 C;
    public static final s03 D;
    public static final s03 E;
    public static final s03 F;
    public static final s03 G;
    public static final s03 H;
    public static final s03 I;
    public static final s03 J;
    public static final s03 K;
    public static final s03 L;
    public static final s03 M;
    public static final s03 N;
    public static final s03 O;
    public static final s03 P;
    public static final s03 Q;
    public static final s03 R;
    public static final s03 S;
    public static final s03 T;
    public static final s03 U;
    public static final s03 V;
    public static final s03 W;
    public static final s03 X;
    public static final s03 Y;
    public static final s03 Z;
    public static final s03 a;

    /* renamed from: a  reason: collision with other field name */
    public static final u7c f20071a = new u7c();
    public static final s03 a0;
    public static final s03 b;
    public static final s03 b0;
    public static final s03 c;
    public static final s03 c0;
    public static final s03 d;
    public static final s03 d0;
    public static final s03 e;
    public static final s03 e0;
    public static final s03 f;
    public static final s03 f0;
    public static final s03 g;
    public static final s03 g0;
    public static final s03 h;
    public static final s03 h0;
    public static final s03 i;
    public static final s03 i0;
    public static final s03 j;
    public static final s03 j0;
    public static final s03 k;
    public static final s03 k0;
    public static final s03 l;
    public static final s03 l0;
    public static final s03 m;
    public static final s03 m0;
    public static final s03 n;
    public static final s03 n0;
    public static final s03 o;
    public static final s03 o0;
    public static final s03 p;
    public static final s03 p0;
    public static final s03 q;
    public static final s03 q0;
    public static final s03 r;
    public static final s03 r0;
    public static final s03 s;
    public static final s03 s0;
    public static final s03 t;
    public static final s03 t0;
    public static final s03 u;
    public static final s03 u0;
    public static final s03 v;
    public static final s03 v0;
    public static final s03 w;
    public static final s03 x;
    public static final s03 y;
    public static final s03 z;

    static {
        s03.b a2 = s03.a("systemInfo");
        dlb dlbVar = new dlb();
        dlbVar.a(1);
        a = a2.b(dlbVar.b()).a();
        s03.b a3 = s03.a("eventName");
        dlb dlbVar2 = new dlb();
        dlbVar2.a(2);
        b = a3.b(dlbVar2.b()).a();
        s03.b a4 = s03.a("isThickClient");
        dlb dlbVar3 = new dlb();
        dlbVar3.a(37);
        c = a4.b(dlbVar3.b()).a();
        s03.b a5 = s03.a("clientType");
        dlb dlbVar4 = new dlb();
        dlbVar4.a(61);
        d = a5.b(dlbVar4.b()).a();
        s03.b a6 = s03.a("modelDownloadLogEvent");
        dlb dlbVar5 = new dlb();
        dlbVar5.a(3);
        e = a6.b(dlbVar5.b()).a();
        s03.b a7 = s03.a("customModelLoadLogEvent");
        dlb dlbVar6 = new dlb();
        dlbVar6.a(20);
        f = a7.b(dlbVar6.b()).a();
        s03.b a8 = s03.a("customModelInferenceLogEvent");
        dlb dlbVar7 = new dlb();
        dlbVar7.a(4);
        g = a8.b(dlbVar7.b()).a();
        s03.b a9 = s03.a("customModelCreateLogEvent");
        dlb dlbVar8 = new dlb();
        dlbVar8.a(29);
        h = a9.b(dlbVar8.b()).a();
        s03.b a10 = s03.a("onDeviceFaceDetectionLogEvent");
        dlb dlbVar9 = new dlb();
        dlbVar9.a(5);
        i = a10.b(dlbVar9.b()).a();
        s03.b a11 = s03.a("onDeviceFaceLoadLogEvent");
        dlb dlbVar10 = new dlb();
        dlbVar10.a(59);
        j = a11.b(dlbVar10.b()).a();
        s03.b a12 = s03.a("onDeviceTextDetectionLogEvent");
        dlb dlbVar11 = new dlb();
        dlbVar11.a(6);
        k = a12.b(dlbVar11.b()).a();
        s03.b a13 = s03.a("onDeviceBarcodeDetectionLogEvent");
        dlb dlbVar12 = new dlb();
        dlbVar12.a(7);
        l = a13.b(dlbVar12.b()).a();
        s03.b a14 = s03.a("onDeviceBarcodeLoadLogEvent");
        dlb dlbVar13 = new dlb();
        dlbVar13.a(58);
        m = a14.b(dlbVar13.b()).a();
        s03.b a15 = s03.a("onDeviceImageLabelCreateLogEvent");
        dlb dlbVar14 = new dlb();
        dlbVar14.a(48);
        n = a15.b(dlbVar14.b()).a();
        s03.b a16 = s03.a("onDeviceImageLabelLoadLogEvent");
        dlb dlbVar15 = new dlb();
        dlbVar15.a(49);
        o = a16.b(dlbVar15.b()).a();
        s03.b a17 = s03.a("onDeviceImageLabelDetectionLogEvent");
        dlb dlbVar16 = new dlb();
        dlbVar16.a(18);
        p = a17.b(dlbVar16.b()).a();
        s03.b a18 = s03.a("onDeviceObjectCreateLogEvent");
        dlb dlbVar17 = new dlb();
        dlbVar17.a(26);
        q = a18.b(dlbVar17.b()).a();
        s03.b a19 = s03.a("onDeviceObjectLoadLogEvent");
        dlb dlbVar18 = new dlb();
        dlbVar18.a(27);
        r = a19.b(dlbVar18.b()).a();
        s03.b a20 = s03.a("onDeviceObjectInferenceLogEvent");
        dlb dlbVar19 = new dlb();
        dlbVar19.a(28);
        s = a20.b(dlbVar19.b()).a();
        s03.b a21 = s03.a("onDevicePoseDetectionLogEvent");
        dlb dlbVar20 = new dlb();
        dlbVar20.a(44);
        t = a21.b(dlbVar20.b()).a();
        s03.b a22 = s03.a("onDeviceSegmentationLogEvent");
        dlb dlbVar21 = new dlb();
        dlbVar21.a(45);
        u = a22.b(dlbVar21.b()).a();
        s03.b a23 = s03.a("onDeviceSmartReplyLogEvent");
        dlb dlbVar22 = new dlb();
        dlbVar22.a(19);
        v = a23.b(dlbVar22.b()).a();
        s03.b a24 = s03.a("onDeviceLanguageIdentificationLogEvent");
        dlb dlbVar23 = new dlb();
        dlbVar23.a(21);
        w = a24.b(dlbVar23.b()).a();
        s03.b a25 = s03.a("onDeviceTranslationLogEvent");
        dlb dlbVar24 = new dlb();
        dlbVar24.a(22);
        x = a25.b(dlbVar24.b()).a();
        s03.b a26 = s03.a("cloudFaceDetectionLogEvent");
        dlb dlbVar25 = new dlb();
        dlbVar25.a(8);
        y = a26.b(dlbVar25.b()).a();
        s03.b a27 = s03.a("cloudCropHintDetectionLogEvent");
        dlb dlbVar26 = new dlb();
        dlbVar26.a(9);
        z = a27.b(dlbVar26.b()).a();
        s03.b a28 = s03.a("cloudDocumentTextDetectionLogEvent");
        dlb dlbVar27 = new dlb();
        dlbVar27.a(10);
        A = a28.b(dlbVar27.b()).a();
        s03.b a29 = s03.a("cloudImagePropertiesDetectionLogEvent");
        dlb dlbVar28 = new dlb();
        dlbVar28.a(11);
        B = a29.b(dlbVar28.b()).a();
        s03.b a30 = s03.a("cloudImageLabelDetectionLogEvent");
        dlb dlbVar29 = new dlb();
        dlbVar29.a(12);
        C = a30.b(dlbVar29.b()).a();
        s03.b a31 = s03.a("cloudLandmarkDetectionLogEvent");
        dlb dlbVar30 = new dlb();
        dlbVar30.a(13);
        D = a31.b(dlbVar30.b()).a();
        s03.b a32 = s03.a("cloudLogoDetectionLogEvent");
        dlb dlbVar31 = new dlb();
        dlbVar31.a(14);
        E = a32.b(dlbVar31.b()).a();
        s03.b a33 = s03.a("cloudSafeSearchDetectionLogEvent");
        dlb dlbVar32 = new dlb();
        dlbVar32.a(15);
        F = a33.b(dlbVar32.b()).a();
        s03.b a34 = s03.a("cloudTextDetectionLogEvent");
        dlb dlbVar33 = new dlb();
        dlbVar33.a(16);
        G = a34.b(dlbVar33.b()).a();
        s03.b a35 = s03.a("cloudWebSearchDetectionLogEvent");
        dlb dlbVar34 = new dlb();
        dlbVar34.a(17);
        H = a35.b(dlbVar34.b()).a();
        s03.b a36 = s03.a("automlImageLabelingCreateLogEvent");
        dlb dlbVar35 = new dlb();
        dlbVar35.a(23);
        I = a36.b(dlbVar35.b()).a();
        s03.b a37 = s03.a("automlImageLabelingLoadLogEvent");
        dlb dlbVar36 = new dlb();
        dlbVar36.a(24);
        J = a37.b(dlbVar36.b()).a();
        s03.b a38 = s03.a("automlImageLabelingInferenceLogEvent");
        dlb dlbVar37 = new dlb();
        dlbVar37.a(25);
        K = a38.b(dlbVar37.b()).a();
        s03.b a39 = s03.a("isModelDownloadedLogEvent");
        dlb dlbVar38 = new dlb();
        dlbVar38.a(39);
        L = a39.b(dlbVar38.b()).a();
        s03.b a40 = s03.a("deleteModelLogEvent");
        dlb dlbVar39 = new dlb();
        dlbVar39.a(40);
        M = a40.b(dlbVar39.b()).a();
        s03.b a41 = s03.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        dlb dlbVar40 = new dlb();
        dlbVar40.a(30);
        N = a41.b(dlbVar40.b()).a();
        s03.b a42 = s03.a("aggregatedCustomModelInferenceLogEvent");
        dlb dlbVar41 = new dlb();
        dlbVar41.a(31);
        O = a42.b(dlbVar41.b()).a();
        s03.b a43 = s03.a("aggregatedOnDeviceFaceDetectionLogEvent");
        dlb dlbVar42 = new dlb();
        dlbVar42.a(32);
        P = a43.b(dlbVar42.b()).a();
        s03.b a44 = s03.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        dlb dlbVar43 = new dlb();
        dlbVar43.a(33);
        Q = a44.b(dlbVar43.b()).a();
        s03.b a45 = s03.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        dlb dlbVar44 = new dlb();
        dlbVar44.a(34);
        R = a45.b(dlbVar44.b()).a();
        s03.b a46 = s03.a("aggregatedOnDeviceObjectInferenceLogEvent");
        dlb dlbVar45 = new dlb();
        dlbVar45.a(35);
        S = a46.b(dlbVar45.b()).a();
        s03.b a47 = s03.a("aggregatedOnDeviceTextDetectionLogEvent");
        dlb dlbVar46 = new dlb();
        dlbVar46.a(36);
        T = a47.b(dlbVar46.b()).a();
        s03.b a48 = s03.a("aggregatedOnDevicePoseDetectionLogEvent");
        dlb dlbVar47 = new dlb();
        dlbVar47.a(46);
        U = a48.b(dlbVar47.b()).a();
        s03.b a49 = s03.a("aggregatedOnDeviceSegmentationLogEvent");
        dlb dlbVar48 = new dlb();
        dlbVar48.a(47);
        V = a49.b(dlbVar48.b()).a();
        s03.b a50 = s03.a("pipelineAccelerationInferenceEvents");
        dlb dlbVar49 = new dlb();
        dlbVar49.a(69);
        W = a50.b(dlbVar49.b()).a();
        s03.b a51 = s03.a("remoteConfigLogEvent");
        dlb dlbVar50 = new dlb();
        dlbVar50.a(42);
        X = a51.b(dlbVar50.b()).a();
        s03.b a52 = s03.a("inputImageConstructionLogEvent");
        dlb dlbVar51 = new dlb();
        dlbVar51.a(50);
        Y = a52.b(dlbVar51.b()).a();
        s03.b a53 = s03.a("leakedHandleEvent");
        dlb dlbVar52 = new dlb();
        dlbVar52.a(51);
        Z = a53.b(dlbVar52.b()).a();
        s03.b a54 = s03.a("cameraSourceLogEvent");
        dlb dlbVar53 = new dlb();
        dlbVar53.a(52);
        a0 = a54.b(dlbVar53.b()).a();
        s03.b a55 = s03.a("imageLabelOptionalModuleLogEvent");
        dlb dlbVar54 = new dlb();
        dlbVar54.a(53);
        b0 = a55.b(dlbVar54.b()).a();
        s03.b a56 = s03.a("languageIdentificationOptionalModuleLogEvent");
        dlb dlbVar55 = new dlb();
        dlbVar55.a(54);
        c0 = a56.b(dlbVar55.b()).a();
        s03.b a57 = s03.a("faceDetectionOptionalModuleLogEvent");
        dlb dlbVar56 = new dlb();
        dlbVar56.a(60);
        d0 = a57.b(dlbVar56.b()).a();
        s03.b a58 = s03.a("nlClassifierOptionalModuleLogEvent");
        dlb dlbVar57 = new dlb();
        dlbVar57.a(55);
        e0 = a58.b(dlbVar57.b()).a();
        s03.b a59 = s03.a("nlClassifierClientLibraryLogEvent");
        dlb dlbVar58 = new dlb();
        dlbVar58.a(56);
        f0 = a59.b(dlbVar58.b()).a();
        s03.b a60 = s03.a("accelerationAllowlistLogEvent");
        dlb dlbVar59 = new dlb();
        dlbVar59.a(57);
        g0 = a60.b(dlbVar59.b()).a();
        s03.b a61 = s03.a("toxicityDetectionCreateEvent");
        dlb dlbVar60 = new dlb();
        dlbVar60.a(62);
        h0 = a61.b(dlbVar60.b()).a();
        s03.b a62 = s03.a("toxicityDetectionLoadEvent");
        dlb dlbVar61 = new dlb();
        dlbVar61.a(63);
        i0 = a62.b(dlbVar61.b()).a();
        s03.b a63 = s03.a("toxicityDetectionInferenceEvent");
        dlb dlbVar62 = new dlb();
        dlbVar62.a(64);
        j0 = a63.b(dlbVar62.b()).a();
        s03.b a64 = s03.a("barcodeDetectionOptionalModuleLogEvent");
        dlb dlbVar63 = new dlb();
        dlbVar63.a(65);
        k0 = a64.b(dlbVar63.b()).a();
        s03.b a65 = s03.a("customImageLabelOptionalModuleLogEvent");
        dlb dlbVar64 = new dlb();
        dlbVar64.a(66);
        l0 = a65.b(dlbVar64.b()).a();
        s03.b a66 = s03.a("codeScannerScanApiEvent");
        dlb dlbVar65 = new dlb();
        dlbVar65.a(67);
        m0 = a66.b(dlbVar65.b()).a();
        s03.b a67 = s03.a("codeScannerOptionalModuleEvent");
        dlb dlbVar66 = new dlb();
        dlbVar66.a(68);
        n0 = a67.b(dlbVar66.b()).a();
        s03.b a68 = s03.a("onDeviceExplicitContentCreateLogEvent");
        dlb dlbVar67 = new dlb();
        dlbVar67.a(70);
        o0 = a68.b(dlbVar67.b()).a();
        s03.b a69 = s03.a("onDeviceExplicitContentLoadLogEvent");
        dlb dlbVar68 = new dlb();
        dlbVar68.a(71);
        p0 = a69.b(dlbVar68.b()).a();
        s03.b a70 = s03.a("onDeviceExplicitContentInferenceLogEvent");
        dlb dlbVar69 = new dlb();
        dlbVar69.a(72);
        q0 = a70.b(dlbVar69.b()).a();
        s03.b a71 = s03.a("aggregatedOnDeviceExplicitContentLogEvent");
        dlb dlbVar70 = new dlb();
        dlbVar70.a(73);
        r0 = a71.b(dlbVar70.b()).a();
        s03.b a72 = s03.a("onDeviceSelfieFaceCreateLogEvent");
        dlb dlbVar71 = new dlb();
        dlbVar71.a(74);
        s0 = a72.b(dlbVar71.b()).a();
        s03.b a73 = s03.a("onDeviceSelfieFaceLoadLogEvent");
        dlb dlbVar72 = new dlb();
        dlbVar72.a(75);
        t0 = a73.b(dlbVar72.b()).a();
        s03.b a74 = s03.a("onDeviceSelfieFaceLogEvent");
        dlb dlbVar73 = new dlb();
        dlbVar73.a(76);
        u0 = a74.b(dlbVar73.b()).a();
        s03.b a75 = s03.a("aggregatedOnDeviceSelfieFaceLogEvent");
        dlb dlbVar74 = new dlb();
        dlbVar74.a(77);
        v0 = a75.b(dlbVar74.b()).a();
    }

    @Override // defpackage.cu2
    public final /* bridge */ /* synthetic */ void a(Object obj, Object obj2) {
        cpc cpcVar = (cpc) obj;
        lq6 lq6Var = (lq6) obj2;
        lq6Var.c(a, cpcVar.d());
        lq6Var.c(b, cpcVar.b());
        lq6Var.c(c, null);
        lq6Var.c(d, cpcVar.a());
        lq6Var.c(e, null);
        lq6Var.c(f, null);
        lq6Var.c(g, null);
        lq6Var.c(h, null);
        lq6Var.c(i, null);
        lq6Var.c(j, null);
        lq6Var.c(k, null);
        lq6Var.c(l, null);
        lq6Var.c(m, null);
        lq6Var.c(n, null);
        lq6Var.c(o, null);
        lq6Var.c(p, null);
        lq6Var.c(q, null);
        lq6Var.c(r, null);
        lq6Var.c(s, null);
        lq6Var.c(t, null);
        lq6Var.c(u, null);
        lq6Var.c(v, null);
        lq6Var.c(w, cpcVar.c());
        lq6Var.c(x, null);
        lq6Var.c(y, null);
        lq6Var.c(z, null);
        lq6Var.c(A, null);
        lq6Var.c(B, null);
        lq6Var.c(C, null);
        lq6Var.c(D, null);
        lq6Var.c(E, null);
        lq6Var.c(F, null);
        lq6Var.c(G, null);
        lq6Var.c(H, null);
        lq6Var.c(I, null);
        lq6Var.c(J, null);
        lq6Var.c(K, null);
        lq6Var.c(L, null);
        lq6Var.c(M, null);
        lq6Var.c(N, null);
        lq6Var.c(O, null);
        lq6Var.c(P, null);
        lq6Var.c(Q, null);
        lq6Var.c(R, null);
        lq6Var.c(S, null);
        lq6Var.c(T, null);
        lq6Var.c(U, null);
        lq6Var.c(V, null);
        lq6Var.c(W, null);
        lq6Var.c(X, null);
        lq6Var.c(Y, null);
        lq6Var.c(Z, null);
        lq6Var.c(a0, null);
        lq6Var.c(b0, null);
        lq6Var.c(c0, null);
        lq6Var.c(d0, null);
        lq6Var.c(e0, null);
        lq6Var.c(f0, null);
        lq6Var.c(g0, null);
        lq6Var.c(h0, null);
        lq6Var.c(i0, null);
        lq6Var.c(j0, null);
        lq6Var.c(k0, null);
        lq6Var.c(l0, null);
        lq6Var.c(m0, null);
        lq6Var.c(n0, null);
        lq6Var.c(o0, null);
        lq6Var.c(p0, null);
        lq6Var.c(q0, null);
        lq6Var.c(r0, null);
        lq6Var.c(s0, null);
        lq6Var.c(t0, null);
        lq6Var.c(u0, null);
        lq6Var.c(v0, null);
    }
}
